version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor  # <-- prevent overwriting vendor
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:80"   # Map container nginx port 80 to host port 3000
    restart: unless-stopped