services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - ecommerce_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app   
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true  
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - ecommerce_network


volumes:
  db_data:

networks:
  ecommerce_network:
    driver: bridge
